name: TemplatePlugin
version: '${project.version}'
main: org.crewco.template.Startup
description: "A Template Plugin for 1.7.10"
author: "XST99"

commands:
  reloadconfig:
    description: Reload recipes command
    usage: /reloadconfig